name: SpendWise CI/CD Pipeline


on:

  push:

    branches:

      - main



jobs:


  build-test:


    runs-on: ubuntu-latest


    steps:


    # 1. Get source code

    - name: Checkout Code

      uses: actions/checkout@v4



    # 2. Setup Python

    - name: Setup Python

      uses: actions/setup-python@v5

      with:

        python-version: "3.12"



    # 3. Install required packages

    - name: Install Dependencies

      run: |

        pip install -r requirements.txt



    # 4. Run application tests

    - name: Run Tests

      run: |

        PYTHONPATH=. pytest



    # 5. Setup Docker

    - name: Set up Docker Buildx

      uses: docker/setup-buildx-action@v3



    # 6. Build Docker image

    - name: Build Docker Image

      run: |

        docker build -t spendwise .



    # 7. Login Docker Hub

    - name: Login to Docker Hub

      uses: docker/login-action@v3

      with:

        username: ${{ secrets.DOCKER_USERNAME }}

        password: ${{ secrets.DOCKER_PASSWORD }}



    # 8. Build and Push image

    - name: Build and Push Docker Image

      uses: docker/build-push-action@v5

      with:

        context: .

        push: true

        tags: dimath2006/spendwise:latest